module.exports.title = [
  "The Colour of Magic",
  "The Light Fantastic",
  "Equal Rites",
  "Mort",
  "Sourcery",
  "Wyrd Sisters",
  "Pyramids",
  "Guards! Guards!",
  "Eric",
  "Moving Pictures",
  "Reaper Man",
  "Witches Abroad",
  "Small Gods",
  "Lords and Ladies",
  "Men at Arms",
  "Soul Music",
  "Interesting Times",
  "Maskerade",
  "Feet of Clay",
  "Hogfather",
  "Jingo",
  "The Last Continent",
  "Carpe Jugulum",
  "The Fifth Elephant",
  "The Truth",
  "Thief of Time",
  "The Last Hero",
  "The Amazing Maurice and his Educated Rodents",
  "Night Watch",
  "The Wee Free Men",
  "Monstrous Regiment",
  "A Hat Full of Sky",
  "Going Postal",
  "Thud!",
  "Where’s My Cow?^",
  "Wintersmith",
  "Making Money",
  "Unseen Academicals",
  "I Shall Wear Midnight",
  "Snuff",
  "World of Poo",
  "Raising Steam",
  "The Shepherd’s Crown"
];

module.exports.user = [
  "Achmed the Mad",
  "Adora Belle Dearheart",
  "Brutha",
  "Carcer Dun",
  "Christine",
  "Conina",
  "Dangerous Beans",
  "Darktan",
  "Dios",
  "Doughnut Jimmy",
  "D'regs",
  "Drum Billet",
  "Ella Saturday",
  "Eric Thursley",
  "Eskarina Smith",
  "Esmerelda Margaret Note Spelling of Lancre",
  "Evadne Cake",
  "Evil Harry Dread",
  "Findthee Swing",
  "The Gonne",
  "Harry King",
  "Herrena, the Henna-haired Harridan",
  "Hubert Turvy",
  "Hodgesaargh",
  "Hrun the Barbarian",
  "Imp Y Celyn",
  "J.H.C. Goatberger",
  "Jason Ogg",
  "Jeremy Clockson",
  "John 'Mossy' Lawn",
  "Lavaeolous",
  "Lewton",
  "Lieutenant Blouse",
  "Liessa Dragonlady",
  "Lord Snapcase",
  "Lord Winder",
  "Lupine Wonse",
  "Ly Tin Wheedle",
  "Marietta Cosmopolite",
  "Maurice",
  "Mavolio Bent",
  "Mightily Oats",
  "Mort",
  "Mr Hong",
  "Mr Pin",
  "Mr Salzella",
  "Mr Tulip",
  "Nijel the Destroyer",
  "Olaf Quimby II",
  "Polly Perks",
  "Princess/Queen Kelirehenna (Keli)",
  "Pteppicymon XXVIII (Pteppic)",
  "Ptraci I",
  "Roland (Roland de Chumsfanleigh)",
  "Ronald Rust, Lord",
  "Rosie Palm, Mrs.",
  "Rufus Drumknott",
  "Sacharissa Cripslock",
  "Sergeant Jackrum",
  "Shawn Ogg",
  "Tawneee (Betty)",
  "Theda 'Ginger' Withel",
  "Victor Tugelbend",
  "Vorbis",
  "Wallace Sonky",
  "Walter Plinge",
  "William de Worde",
  "Willie Hobson",
  "Willikins",
  "Lady Ysabell"
];

module.exports.location = [
  "Ankh-Morpork",
  "Borogravia",
  "Brindisi",
  "The Chalk",
  "Chirm",
  "Chimeria",
  "Copperhead",
  "Cori Celesti",
  "Ecalpon",
  "Genua",
  "Gonim",
  "Holy Wood",
  "Koom Valley",
  "Kythia",
  "Lancre",
  "Llamedos",
  "Mouldavia",
  "NoThingfjord",
  "Octarine Grass Country",
  "Ohulan Cutash",
  "Oi Dong",
  "Pseudopolis",
  "Quirm",
  "Rehigreed Province",
  "Skund",
  "Sto Helit",
  "Sto Kerrig",
  "Sto Lat",
  "Überwald",
  "The Wyrmberg",
  "Zemphis",
  "Zlobenia"
];

module.exports.description = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "Curabitur pulvinar id tellus nec lacinia.",
  "Nam quis facilisis est. Quisque fermentum eleifend mi, porta tempus ante sodales id.",
  "Nullam sit amet rutrum massa. Phasellus ligula velit, lobortis nec orci quis, luctus dignissim mauris.",
  "Donec ullamcorper faucibus metus, et ornare neque molestie pretium.",
  "Nunc nisi nisi, volutpat ut elementum eget, tempor quis quam.",
  "Nullam sagittis enim iaculis dolor molestie, facilisis maximus ipsum tristique.",
  "Nunc sollicitudin nec augue quis volutpat. Aenean ante dui, pretium non sem sit amet, pulvinar consequat neque.",
  "Suspendisse cursus, massa ac accumsan vulputate, nunc nisl mollis dui, quis ultrices ante metus sit amet arcu.",
  "Ut nisi ex, dignissim ac metus eu, vulputate efficitur metus."
];
