module.exports.title = [
  "The Colour of Magic",
  "The Light Fantastic",
  "Equal Rites",
  "Mort",
  "Sourcery",
  "Wyrd Sisters",
  "Pyramids",
  "Guards! Guards!",
  "Eric",
  "Moving Pictures",
  "Reaper Man",
  "Witches Abroad",
  "Small Gods",
  "Lords and Ladies",
  "Men at Arms",
  "Soul Music",
  "Interesting Times",
  "Maskerade",
  "Feet of Clay",
  "Hogfather",
  "Jingo",
  "The Last Continent",
  "Carpe Jugulum",
  "The Fifth Elephant",
  "The Truth",
  "Thief of Time",
  "The Last Hero",
  "The Amazing Maurice and his Educated Rodents",
  "Night Watch",
  "The Wee Free Men",
  "Monstrous Regiment",
  "A Hat Full of Sky",
  "Going Postal",
  "Thud!",
  "Where’s My Cow?^",
  "Wintersmith",
  "Making Money",
  "Unseen Academicals",
  "I Shall Wear Midnight",
  "Snuff",
  "World of Poo",
  "Raising Steam",
  "The Shepherd’s Crown"
];

module.exports.user = [
  "Achmed the Mad",
  "Adora Belle Dearheart",
  "Brutha",
  "Carcer Dun",
  "Christine",
  "Conina",
  "Dangerous Beans",
  "Darktan",
  "Dios",
  "Doughnut Jimmy",
  "D'regs",
  "Drum Billet",
  "Ella Saturday",
  "Eric Thursley",
  "Eskarina Smith",
  "Esmerelda Margaret Note Spelling of Lancre",
  "Evadne Cake",
  "Evil Harry Dread",
  "Findthee Swing",
  "The Gonne",
  "Harry King",
  "Herrena, the Henna-haired Harridan",
  "Hubert Turvy",
  "Hodgesaargh",
  "Hrun the Barbarian",
  "Imp Y Celyn",
  "J.H.C. Goatberger",
  "Jason Ogg",
  "Jeremy Clockson",
  "John 'Mossy' Lawn",
  "Lavaeolous",
  "Lewton",
  "Lieutenant Blouse",
  "Liessa Dragonlady",
  "Lord Snapcase",
  "Lord Winder",
  "Lupine Wonse",
  "Ly Tin Wheedle",
  "Marietta Cosmopolite",
  "Maurice",
  "Mavolio Bent",
  "Mightily Oats",
  "Mort",
  "Mr Hong",
  "Mr Pin",
  "Mr Salzella",
  "Mr Tulip",
  "Nijel the Destroyer",
  "Olaf Quimby II",
  "Polly Perks",
  "Princess/Queen Kelirehenna (Keli)",
  "Pteppicymon XXVIII (Pteppic)",
  "Ptraci I",
  "Roland (Roland de Chumsfanleigh)",
  "Ronald Rust, Lord",
  "Rosie Palm, Mrs.",
  "Rufus Drumknott",
  "Sacharissa Cripslock",
  "Sergeant Jackrum",
  "Shawn Ogg",
  "Tawneee (Betty)",
  "Theda 'Ginger' Withel",
  "Victor Tugelbend",
  "Vorbis",
  "Wallace Sonky",
  "Walter Plinge",
  "William de Worde",
  "Willie Hobson",
  "Willikins",
  "Lady Ysabell"
];

module.exports.location = [
  "Ankh-Morpork",
  "Borogravia",
  "Brindisi",
  "The Chalk",
  "Chirm",
  "Chimeria",
  "Copperhead",
  "Cori Celesti",
  "Ecalpon",
  "Genua",
  "Gonim",
  "Holy Wood",
  "Koom Valley",
  "Kythia",
  "Lancre",
  "Llamedos",
  "Mouldavia",
  "NoThingfjord",
  "Octarine Grass Country",
  "Ohulan Cutash",
  "Oi Dong (see also History Monks & Enlightenment country)",
  "Pseudopolis",
  "Quirm",
  "Rehigreed Province",
  "Skund",
  "Sto Helit",
  "Sto Kerrig",
  "Sto Lat",
  "Überwald",
  "The Wyrmberg",
  "Zemphis",
  "Zlobenia"
];

module.exports.description = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean semper libero velit, id efficitur quam pharetra ac. Fusce tempor id enim id iaculis. Phasellus id velit at metus tincidunt iaculis ut a nibh. Nunc eget rutrum mauris, sit amet porttitor ipsum. Nunc pretium nulla rhoncus, facilisis massa eu, scelerisque nulla. Proin elit nunc, lobortis non neque non, eleifend feugiat nisi. Nam vehicula gravida velit, vitae finibus ex rhoncus quis. Aenean vulputate id sem eu tempor. Nunc facilisis vestibulum pellentesque. Nulla accumsan enim dui, quis vehicula ipsum volutpat in. Nulla volutpat urna vel pellentesque luctus. Vivamus mollis fermentum erat, ac lacinia odio lacinia quis. Donec porta eu leo ac sodales. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus quam dolor, placerat vitae consectetur sit amet, venenatis ut felis.",
  "Curabitur pulvinar id tellus nec lacinia. Phasellus mi eros, dictum non lectus et, accumsan molestie mauris. Nam tristique facilisis cursus. Curabitur quis bibendum massa. Donec congue, nisl ac faucibus malesuada, lorem erat mollis felis, sed sollicitudin lorem diam a augue. Donec ipsum diam, rhoncus eu blandit nec, ultrices nec lorem. Ut orci nunc, lacinia ut accumsan ac, mollis quis justo. Maecenas vitae turpis elementum, ornare turpis quis, feugiat turpis. Pellentesque quis imperdiet elit. Aliquam at metus gravida, ullamcorper purus aliquam, vehicula ante. Vivamus elementum, risus id elementum dictum, risus lacus dapibus urna, et varius eros turpis quis elit. Ut sed massa placerat magna ultrices porttitor. Sed eleifend vitae neque sit amet aliquam. Nulla orci augue, tincidunt ut gravida id, malesuada quis dui. Nunc ultrices leo sit amet est hendrerit convallis. Phasellus massa mi, varius et lacinia ac, sollicitudin quis lectus.",
  "Nam quis facilisis est. Quisque fermentum eleifend mi, porta tempus ante sodales id. Maecenas in ultrices tortor. Pellentesque quam orci, tincidunt sit amet porta in, fringilla a odio. In euismod vehicula iaculis. Aliquam eget tempor mauris, et tempus quam. Vestibulum at neque venenatis, ullamcorper quam commodo, commodo magna.",
  "Nullam sit amet rutrum massa. Phasellus ligula velit, lobortis nec orci quis, luctus dignissim mauris. Pellentesque non neque eget tortor consequat molestie. Vestibulum libero ligula, facilisis eleifend mi vel, vulputate accumsan lacus. Integer vitae interdum metus. Vivamus sit amet lorem felis. Vivamus imperdiet volutpat imperdiet. Suspendisse tempor est a sem placerat consectetur. Sed justo nibh, feugiat sit amet ultrices et, interdum a nisi. Aenean lectus velit, porttitor vitae dolor eu, molestie posuere ex. Duis quis maximus magna. Proin blandit sem diam, quis fermentum elit faucibus in.",
  "Donec ullamcorper faucibus metus, et ornare neque molestie pretium. Integer varius dignissim nulla, ac tempus diam lacinia sed. Aliquam rhoncus eu sapien at auctor. Aenean congue nisl at erat ultrices gravida. Morbi pellentesque nec dolor eget pretium. Nullam vel tincidunt odio. Etiam ipsum eros, rutrum ut faucibus id, malesuada ut ante. Duis sed tincidunt purus, vitae lobortis diam. Morbi elementum, augue eget facilisis ornare, nulla nulla mollis enim, quis porttitor massa dolor quis augue. Maecenas sagittis sed sem vitae vestibulum. Vestibulum tincidunt enim ultricies, sagittis ligula vel, finibus quam. Proin eget purus enim. In imperdiet ligula eget metus iaculis semper. Nunc ligula nunc, vulputate vitae augue id, facilisis auctor velit.",
  "Nunc nisi nisi, volutpat ut elementum eget, tempor quis quam. Nam at sodales nunc, a malesuada ante. Phasellus ut mauris vel augue lacinia vehicula scelerisque at mi. Proin in sapien at leo sagittis commodo cursus at purus. Curabitur ultricies euismod eros at vehicula. Curabitur condimentum eleifend nibh, sed sodales magna sollicitudin eget. Integer sed diam purus.",
  "Nullam sagittis enim iaculis dolor molestie, facilisis maximus ipsum tristique. Ut a erat eget leo scelerisque ullamcorper. Aenean at metus odio. Phasellus ultricies rutrum diam, vitae congue urna semper non. Mauris cursus, velit et venenatis tempus, sapien lacus maximus velit, vel pulvinar metus ipsum vel neque. In ornare molestie odio, quis feugiat tortor accumsan vitae. Sed cursus purus vitae fringilla sollicitudin. Morbi congue imperdiet odio in tristique. Suspendisse eu consectetur diam, ac dictum metus.",
  "Nunc sollicitudin nec augue quis volutpat. Aenean ante dui, pretium non sem sit amet, pulvinar consequat neque. Nullam eget quam malesuada, lobortis ligula et, suscipit enim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras in dapibus ex, vitae elementum sapien. Aliquam in erat id quam consectetur feugiat et quis magna. Etiam justo sapien, suscipit in vulputate et, dapibus eu dui. Pellentesque eget ligula ac sem cursus pharetra vitae ultricies quam. Nunc ornare est et leo faucibus, sed pharetra erat tincidunt. Maecenas laoreet feugiat nulla, quis ullamcorper eros. Mauris neque massa, vestibulum eget laoreet ut, egestas quis mi.",
  "Suspendisse cursus, massa ac accumsan vulputate, nunc nisl mollis dui, quis ultrices ante metus sit amet arcu. In hac habitasse platea dictumst. Pellentesque diam ligula, porta facilisis viverra ut, pharetra nec dui. Nullam egestas mi in neque ornare, posuere facilisis justo scelerisque. Quisque iaculis eros nisl, in dictum ex elementum quis. Phasellus porta urna eget eros gravida eleifend. Morbi quis nisi non lorem posuere cursus. Fusce nec eleifend nunc. Praesent mollis vel ipsum eget vestibulum. Pellentesque auctor viverra nisl, vitae tempor arcu vehicula ac.",
  "Ut nisi ex, dignissim ac metus eu, vulputate efficitur metus. Donec fermentum, arcu quis vestibulum iaculis, elit lacus luctus lorem, vel facilisis arcu nunc sit amet nibh. Aenean bibendum eget elit at cursus. Nam in euismod quam. Sed finibus libero eu velit imperdiet, a mollis ante ultricies. Vestibulum quis elit facilisis, varius ante ac, porttitor neque. Etiam est ex, blandit non consectetur et, ultricies in lectus. Donec sit amet felis vitae sem iaculis pharetra. Maecenas mattis, quam nec mattis suscipit, arcu enim aliquam urna, ut sodales diam massa sit amet felis. Morbi dictum lacus dui, ut bibendum enim aliquam vel."
];